# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermember',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usermember',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='username',
        ),
        migrations.AlterField(
            model_name='usermember',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
