# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='token',
            field=models.CharField(default='8fbbc786af414f7c9ab452d63bc75b26', max_length=50),
        ),
    ]
