# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usermember_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='token',
            field=models.CharField(default='593ed5272edc49c49b92366e14c52944', max_length=50),
        ),
    ]
