# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170307_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='token',
            field=models.CharField(default='9348a7a0198b47839fea7c22c7f5a0d4', max_length=50),
        ),
    ]
