# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170227_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
    ]
