# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170307_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='token',
            field=models.CharField(default='445a116003374dcbbcb29cb726a58d33', max_length=50),
        ),
    ]
