# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170307_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='token',
            field=models.CharField(default='302cd55548c445b3a95df0b6dda76a3c', max_length=250, unique=True),
        ),
    ]
