# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170307_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='token',
            field=models.CharField(default='8beea59701d14036a00808e3a149a111', max_length=250),
        ),
    ]
