# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170307_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='token',
            field=models.CharField(default='397322e450d74e1e88e3648a5919f7be', max_length=50),
        ),
    ]
