# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170307_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='token',
            field=models.CharField(default='ecbfe2ab54fe482585ff861f1f985051', max_length=50),
        ),
    ]
